# Spring Configuration
spring:
  application:
    name: payment
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mujiki_payment
    username: mujiki_payment
    password: nothing

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:logs/db.changelog-master.xml
    enabled: true

# API Configuration
api:
  endpoint:
    base-url: /api

address:
  url:
    service: http://localhost:86/api/address

user:
  url:
    service: http://localhost:81/api/user


# Server Configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 87



